site_name: École de Neuropsychologie
theme: readthedocs
pages:
- Home: index.md
- Clinical Practice:
  - Neuropsychopharmacology: ClinicalPractice/Neuropsychopharmacology/Antidepressants.md
- Creating Experiments and Tests:
  - Neuropsydia.py:
    - Documentation:
      - Tutorials:
        - Novice: CreatingExperiments/Neuropsydia.py/Tutorials/Novice.md
        - Apprentice: CreatingExperiments/Neuropsydia.py/Tutorials/Apprentice.md
- Data Science:
  - R:
    - Introduction: DataScience/R/Introduction.md
    - Data Manipulation: DataScience/R/DataManipulation.md
    - Mixed Modeling: DataScience/R/MixedModeling.md
- Contributing: Contributing/Contribute.md
- About:
  - People: About/people.md