site_name: École de Neuropsychologie
theme: readthedocs
site_description: 'Courses on Neuropsychology, Statistics, Programming and more.'
site_author: 'Dominique Makowski'
repo_url: https://github.com/neuropsychology/Courses/

pages:
- Home: index.md
- Clinical Practice:
  - Neuropsychopharmacology: ClinicalPractice/Neuropsychopharmacology/Antidepressants.md
- Creating Experiments and Tests:
  - Neuropsydia.py:
    - Documentation:
    - Tutorials:
      - 1. Novice:
        - 1. Getting Started: CreatingExperiments/Neuropsydia.py/Tutorials/Novice/Getting_Started.md
        - 2. Computerize a Questionnaire: CreatingExperiments/Neuropsydia.py/Tutorials/Novice/Computerize_Questionnaire.md
        - 3. Complexify this Questionnaire: CreatingExperiments/Neuropsydia.py/Tutorials/Novice/Complexify_Questionnaire.md
        - 4. Include Info: CreatingExperiments/Neuropsydia.py/Tutorials/Novice/Include_Info_Participant.md
      - 2. Apprentice: CreatingExperiments/Neuropsydia.py/Tutorials/Apprentice.md
- Data Science:
  - R:
    - Introduction: DataScience/R/Introduction.md
    - Data Manipulation: DataScience/R/DataManipulation.md
    - Mixed Modeling: DataScience/R/MixedModeling.md
  - Python:
    - Signal Processing:
      - EDA: DataScience/Python/SignalProcessing/EDA.md
- Contributing: Contributing/Contribute.md
- About:
  - People: About/people.md
